{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: {{ include "kuberay-operator.fullname" . }}
{{ include "role.consistentRules" (dict "batchSchedulerEnabled" .Values.batchScheduler.enabled) }}
{{- end }}
